<<<<<<< HEAD
redis:
  host: pcthink.local
  port: 6379
mqtt:
  host: pcthink.local
  port: 1883
screen:
  resolution: [1024,768]
  grid_size: 32
status:
  label: "USB0 System Alive"
  src_topic: src/USB0/system/alive
  src_value: true
  src_timeout: 3000
=======
mqtt:
  host: "pcthink.local"
  port: 1883
redis:
  host: "pcthink.local"
  port: 6379

label_heap-shaker1:
  suffix: " Bytes"
  prefix: "Shaker1 Heap : "
  pos: [0,0]
  size: [30,100]
  src_topic: "src/shaker1/system/heap"
button_shake:
  label: "Shake"
  pos: [3,3]
  size: [30,300]
  dst_topic: "dst/shaker2/shaker/shake"
label_shaker1-latency:
  suffix: " usec"
  prefix: "Latency : "
  pos: [6,6]
  size: [30,200]
  src_topic: "src/shaker1/system/latency"


  
>>>>>>> 61768f29e7f14a9abe3a9e54700a11af77cbc114
